version: "3.9"
name: microservice-gateway-example

services:
  postgres-keycloak:
    container_name: postgres-keycloak
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    expose:
      - "5432"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_HOSTNAME: localhost
      KC_DB_PASSWORD: admin
      KC_DB_USERNAME: admin
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_URL_PORT: 5432
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "18080:8080"
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'
    volumes:
      - ./keycloak-exports:/opt/keycloak/data/import
    depends_on:
      - postgres-keycloak

  greeting-service:
    container_name: greeting-service
    build:
      context: ./greeting-service
    restart: unless-stopped
    depends_on:
      - keycloak

  gateway:
    container_name: gateway
    build:
      context: ./gateway
    restart: unless-stopped
    ports:
      - "8080:8081"
    environment:
      KEYCLOAK_URI: http://localhost:18080
      KEYCLOAK_URI_INTERNAL: http://keycloak:8080
      GREETING-SERVICE-URI: http://greeting-service:8082
    depends_on:
      - greeting-service
      - keycloak
volumes:
  postgres-db:
